### ISSUE TITLE
update terraform version and code to 1.1.4 (latest)

### ISSUE THREAD

**Issue by michalbagrowski** [aeternity/terraform-aws-apps#4]

**Comment by michalbagrowski** [comment]
@dincho @mmpetarpeshev looks liek this repository is update outside pipelines, does we should work on it?

**Comment by dincho** [comment]
@michalbagrowski Yes, not pipelines. I was alone when I started then mostly @mmpetarpeshev works alone on it. Please coordinate in the group any changes with him (until we have a pipeline). Or you could add a pipeline :)
